version: '3'
services:
    mongo:
        image: 'mongo'
    microdraw:
        container_name: microdraw
        depends_on:
            - 'mongo'
        build: ..
        image: microdraw
        ports:
            - '3000:3000'
        environment:
            - MONGODB=mongodb://mongo:27017/microdraw
            - TOKEN_DURATION=86400000